import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import Header from "./header";
import Footer from "./footer";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Loyalty Program Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <Header />
        <body className={`${geistMono.variable} antialiased mb-10`}>
          {children}
        </body>
        <Footer />
      </html>
      <Toaster dir="ltr" position="top-right" duration={2000} />
    </>
  );
}
